version: '3'

networks:
  spring-starter-kit-network:

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - /secret/spring-starter-kit/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - spring-starter-kit-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - spring-starter-kit-network