spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never
  datasource:
    url: ${DEV_MYSQL_DATABASE_URL}
    username: ${DEV_MYSQL_USERNAME}
    password: ${DEV_MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none