spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/stock_news_collect_db

  main:
    allow-bean-definition-overriding: true

newsapi:
  key: ac210c6254fc4b089710ed8930819655
  url: https://newsapi.org/v2/everything

logging:
  level:
    root: INFO
    com.devty.stocknewsanalyzer: DEBUG