global:
  scrape_interval: 10s # 10초 마다 Metric을 Pulling
  evaluation_interval: 10s # rule 을 얼마나 빈번하게 검증하는지 설정

scrape_configs:
  - job_name: 'spring-starter-kit-actuator-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-starter-kit:8080'] # service 이름으로 지정